export type IconName = 
      "arrowDown"
    | "arrowUp"
    | "bold"
    | "blockquote"
    | "diskette"
    | "eye"
    | "heading1"
    | "heading2"
    | "heading3"
    | "heading4"
    | "heading5"
    | "heading6"
    | "italic"
    | "menu"
    | "paragraph"
    | "pencil"
    | "plus"
    | "strikethrough"
    | "trashBin"
    | "underline"
    | "x";

