import { IconName } from "../types/icon-name";

export const IconNameMap: { [key in IconName]: IconName } = {
    "arrowDown": "arrowDown",
    "arrowUp": "arrowUp",
    "blockquote": "blockquote",
    "bold": "arrowDown",
    "diskette": "diskette",
    "eye": "eye",
    "heading1": "heading1",
    "heading2": "heading2",
    "heading3": "heading3",
    "heading4": "heading4",
    "heading5": "heading5",
    "heading6": "heading6",
    "italic": "arrowDown",
    "menu": "menu",
    "paragraph": "paragraph",
    "pencil": "pencil",
    "plus": "plus",
    "strikethrough": "arrowDown",
    "trashBin": "trashBin",
    "underline": "arrowDown",
    "x": "x",
};
