export * from "./icon-arrow-up";
export * from "./icon-arrow-down";
export * from "./icon-doublequote";
export * from "./icon-heading-1";
export * from "./icon-heading-2";
export * from "./icon-paragraph";
export * from "./icon-plus";
export * from "./icon-trash-bin";
export * from "./icon-x";
