export * from "./icon-arrow-down";
export * from "./icon-arrow-up";
export * from "./icon-bold";
export * from "./icon-doublequote";
export * from "./icon-eye";
export * from "./icon-heading-1";
export * from "./icon-heading-2";
export * from "./icon-heading-3";
export * from "./icon-heading-4";
export * from "./icon-heading-5";
export * from "./icon-heading-6";
export * from "./icon-italic";
export * from "./icon-menu";
export * from "./icon-paragraph";
export * from "./icon-pencil";
export * from "./icon-plus";
export * from "./icon-strikethrough"
export * from "./icon-trash-bin";
export * from "./icon-underline";
export * from "./icon-x";

